---
# Define root password for percona server
root_password: superdupersecretpassword

# Some defaults variables for percona server config file
port: 3306
data_dir: /var/lib/mysql
bind_address: 0.0.0.0
max_allowed_packet: 16M
key_buffer: 16M
thread_stack: 192K
thread_cache_size: 8

slow_query_log: 0
slow_query_log_file: /var/log/mysql/mysql-slow.log
long_query_time: 2

log_queries_not_using_indexes: 0
log_bin: /var/lib/mysql/mysql-bin

expire_logs_days: 14

innodb_buffer_pool_size: 1G
innodb_log_file_size: 512M
innodb_file_per_table: 1

table_open_cache: 100
thread_cache_size: 50
max_connections: 500
max_heap_table_size: 32M
tmp_table_size: 32M

# Define is a database must be created
create_app_db: true
db_name: mydatabase
db_collation: utf8_general_ci
db_user: myuser
db_user_password: thisismysupersecretpassword
db_host: "%"
db_dump_file: ""

galera_cone values are default - change for security!
galera_conf:
    bind_address: 0.0.0.0
    dbusers:
        xtrabackup:
            username: xtrabackup 
            password: xtrabackup 
        docker:
            username: docker 
            password: docker 
            host: 172.17.%
        clustercheck:
            username: clustercheck
            password: clustercheck:
    bind_address: 0.0.0.0
    dbusers:
        xtrabackup:
            username: xtrabackup 
            password: xtrabackup 
        docker:
            username: docker 
            password: docker 
            host: 172.17.%
        clustercheck:
            username: clustercheck
            password: clustercheck
