####
## Install, configure Munin-node
#
---
  
# Ensure munin-node is installed
- name: Ensure munin-node package is installed
  apt: pkg=munin-node state=installed

- name: Install Munin Master Node
  apt: pkg={{ item }} state=installed
  when: munin_master
  with_items:
      - munin
      - munin-node

- name: copy over munin-node.conf
  template: src=munin-node.conf.jinja dest=/etc/munin/munin-node.conf mode=644
  notify: restart munin-node

- name: replace munin.conf on master
  template: src=munin.conf.jinja dest=/etc/munin/munin.conf mode=0644
  when: munin_master

